apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: '{{ .InstanceID }}'
nameSuffix: "{{ .InstanceSuffix }}"

resources:
- namespace-install.yaml

patches:
# Remove all CRDs
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: .*
  patch: |-
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important
