/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/numaproj/numaplane/pkg/apis/numaplane/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ISBServiceRolloutLister helps list ISBServiceRollouts.
// All objects returned here must be treated as read-only.
type ISBServiceRolloutLister interface {
	// List lists all ISBServiceRollouts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ISBServiceRollout, err error)
	// ISBServiceRollouts returns an object that can list and get ISBServiceRollouts.
	ISBServiceRollouts(namespace string) ISBServiceRolloutNamespaceLister
	ISBServiceRolloutListerExpansion
}

// iSBServiceRolloutLister implements the ISBServiceRolloutLister interface.
type iSBServiceRolloutLister struct {
	indexer cache.Indexer
}

// NewISBServiceRolloutLister returns a new ISBServiceRolloutLister.
func NewISBServiceRolloutLister(indexer cache.Indexer) ISBServiceRolloutLister {
	return &iSBServiceRolloutLister{indexer: indexer}
}

// List lists all ISBServiceRollouts in the indexer.
func (s *iSBServiceRolloutLister) List(selector labels.Selector) (ret []*v1alpha1.ISBServiceRollout, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ISBServiceRollout))
	})
	return ret, err
}

// ISBServiceRollouts returns an object that can list and get ISBServiceRollouts.
func (s *iSBServiceRolloutLister) ISBServiceRollouts(namespace string) ISBServiceRolloutNamespaceLister {
	return iSBServiceRolloutNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ISBServiceRolloutNamespaceLister helps list and get ISBServiceRollouts.
// All objects returned here must be treated as read-only.
type ISBServiceRolloutNamespaceLister interface {
	// List lists all ISBServiceRollouts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ISBServiceRollout, err error)
	// Get retrieves the ISBServiceRollout from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ISBServiceRollout, error)
	ISBServiceRolloutNamespaceListerExpansion
}

// iSBServiceRolloutNamespaceLister implements the ISBServiceRolloutNamespaceLister
// interface.
type iSBServiceRolloutNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ISBServiceRollouts in the indexer for a given namespace.
func (s iSBServiceRolloutNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ISBServiceRollout, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ISBServiceRollout))
	})
	return ret, err
}

// Get retrieves the ISBServiceRollout from the indexer for a given namespace and name.
func (s iSBServiceRolloutNamespaceLister) Get(name string) (*v1alpha1.ISBServiceRollout, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("isbservicerollout"), name)
	}
	return obj.(*v1alpha1.ISBServiceRollout), nil
}
