/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/numaproj/numaplane/pkg/apis/numaplane/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// NumaflowControllerRolloutLister helps list NumaflowControllerRollouts.
// All objects returned here must be treated as read-only.
type NumaflowControllerRolloutLister interface {
	// List lists all NumaflowControllerRollouts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.NumaflowControllerRollout, err error)
	// NumaflowControllerRollouts returns an object that can list and get NumaflowControllerRollouts.
	NumaflowControllerRollouts(namespace string) NumaflowControllerRolloutNamespaceLister
	NumaflowControllerRolloutListerExpansion
}

// numaflowControllerRolloutLister implements the NumaflowControllerRolloutLister interface.
type numaflowControllerRolloutLister struct {
	listers.ResourceIndexer[*v1alpha1.NumaflowControllerRollout]
}

// NewNumaflowControllerRolloutLister returns a new NumaflowControllerRolloutLister.
func NewNumaflowControllerRolloutLister(indexer cache.Indexer) NumaflowControllerRolloutLister {
	return &numaflowControllerRolloutLister{listers.New[*v1alpha1.NumaflowControllerRollout](indexer, v1alpha1.Resource("numaflowcontrollerrollout"))}
}

// NumaflowControllerRollouts returns an object that can list and get NumaflowControllerRollouts.
func (s *numaflowControllerRolloutLister) NumaflowControllerRollouts(namespace string) NumaflowControllerRolloutNamespaceLister {
	return numaflowControllerRolloutNamespaceLister{listers.NewNamespaced[*v1alpha1.NumaflowControllerRollout](s.ResourceIndexer, namespace)}
}

// NumaflowControllerRolloutNamespaceLister helps list and get NumaflowControllerRollouts.
// All objects returned here must be treated as read-only.
type NumaflowControllerRolloutNamespaceLister interface {
	// List lists all NumaflowControllerRollouts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.NumaflowControllerRollout, err error)
	// Get retrieves the NumaflowControllerRollout from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.NumaflowControllerRollout, error)
	NumaflowControllerRolloutNamespaceListerExpansion
}

// numaflowControllerRolloutNamespaceLister implements the NumaflowControllerRolloutNamespaceLister
// interface.
type numaflowControllerRolloutNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.NumaflowControllerRollout]
}
