/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/numaproj/numaplane/pkg/apis/numaplane/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PipelineRolloutLister helps list PipelineRollouts.
// All objects returned here must be treated as read-only.
type PipelineRolloutLister interface {
	// List lists all PipelineRollouts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.PipelineRollout, err error)
	// PipelineRollouts returns an object that can list and get PipelineRollouts.
	PipelineRollouts(namespace string) PipelineRolloutNamespaceLister
	PipelineRolloutListerExpansion
}

// pipelineRolloutLister implements the PipelineRolloutLister interface.
type pipelineRolloutLister struct {
	indexer cache.Indexer
}

// NewPipelineRolloutLister returns a new PipelineRolloutLister.
func NewPipelineRolloutLister(indexer cache.Indexer) PipelineRolloutLister {
	return &pipelineRolloutLister{indexer: indexer}
}

// List lists all PipelineRollouts in the indexer.
func (s *pipelineRolloutLister) List(selector labels.Selector) (ret []*v1alpha1.PipelineRollout, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PipelineRollout))
	})
	return ret, err
}

// PipelineRollouts returns an object that can list and get PipelineRollouts.
func (s *pipelineRolloutLister) PipelineRollouts(namespace string) PipelineRolloutNamespaceLister {
	return pipelineRolloutNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// PipelineRolloutNamespaceLister helps list and get PipelineRollouts.
// All objects returned here must be treated as read-only.
type PipelineRolloutNamespaceLister interface {
	// List lists all PipelineRollouts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.PipelineRollout, err error)
	// Get retrieves the PipelineRollout from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.PipelineRollout, error)
	PipelineRolloutNamespaceListerExpansion
}

// pipelineRolloutNamespaceLister implements the PipelineRolloutNamespaceLister
// interface.
type pipelineRolloutNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all PipelineRollouts in the indexer for a given namespace.
func (s pipelineRolloutNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.PipelineRollout, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PipelineRollout))
	})
	return ret, err
}

// Get retrieves the PipelineRollout from the indexer for a given namespace and name.
func (s pipelineRolloutNamespaceLister) Get(name string) (*v1alpha1.PipelineRollout, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("pipelinerollout"), name)
	}
	return obj.(*v1alpha1.PipelineRollout), nil
}
