apiVersion: numaplane.numaproj.io/v1alpha1
kind: ISBServiceRollout
metadata:
  name: simple-isbservice
spec:
  interStepBufferService:
    spec:
      jetstream:
        replicas: 1
        version: latest
        persistence:
          volumeSize: 1Gi
