# permissions for end users to view monovertexrollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: numaplane
    app.kubernetes.io/managed-by: kustomize
  name: monovertexrollout-viewer-role
rules:
- apiGroups:
  - numaplane.numaproj.io
  resources:
  - monovertexrollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - numaplane.numaproj.io
  resources:
  - monovertexrollouts/status
  verbs:
  - get
