apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: numaplane-aggregate-to-view
rules:
  - apiGroups:
    - numaplane.numaproj.io
    resources:
    - pipelinerollouts
    - isbservicerollouts
    - numaflowcontrollerrollouts
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - numaplane.numaproj.io
    resources:
    - pipelinerollouts/status
    - isbservicerollouts/status
    - numaflowcontrollerrollouts/status
    verbs:
    - get