# permissions for end users to edit numaflowcontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: numaplane
    app.kubernetes.io/managed-by: kustomize
  name: numaflowcontroller-editor-role
rules:
- apiGroups:
  - numaplane.numaproj.io.github.com.numaproj
  resources:
  - numaflowcontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - numaplane.numaproj.io.github.com.numaproj
  resources:
  - numaflowcontrollers/status
  verbs:
  - get
