apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: numaplane-aggregate-to-admin
rules:
  - apiGroups:
    - numaplane.numaproj.io
    resources:
    - pipelinerollouts
    - isbservicerollouts
    - numaflowcontrollerrollouts
    - monovertexrollouts
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - numaplane.numaproj.io
    resources:
    - pipelinerollouts/status
    - isbservicerollouts/status
    - numaflowcontrollerrollouts/status
    - monovertexrollouts/status
    verbs:
    - get
    
  