blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://github.com/numaproj-labs/numaplane
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/numaproj-labs/numaplane/discussions/new
    about: Ask a question or start a discussion about Numaplane