apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: example-namespace
  labels:
    numaplane.numaproj.io/config: namespace-level-config
data:
  # strategy can be either "progressive" or "pause-and-drain"
  strategy: "progressive"
