apiVersion: numaplane.numaproj.io/v1alpha1
kind: PipelineRollout
metadata:
  name: my-pipeline
  namespace: example-namespace
spec:
  pipeline:
    #uncomment for Progressive rollout to set Numaflow Controller instance:
    metadata:
      annotations:
        numaflow.numaproj.io/instance: "0"
    spec:
      interStepBufferServiceName: my-isbsvc-0
      vertices:
        - name: in
          source:
            # A self data generating source
            generator:
              rpu: 5
              duration: 2s
        #- name: cat
        #  udf:
        #    builtin:
        #      name: cat # A built-in UDF which simply cats the message
        - name: out
          sink:
            # A simple log printing sink
            log: {}
      edges:
        - from: in
          to: cat
        - from: cat
          to: out
