apiVersion: numaplane.numaproj.io/v1alpha1
kind: PipelineRollout
metadata:
  name: my-pipeline
  namespace: example-namespace
spec:
  strategy:
    #progressive: # only required if we need to override the defaults in numaplane-controller-config ConfigMap
    #  assessmentSchedule: "10,200,60,10"
    analysis:
      templates:
      - templateName: pipeline-template
        clusterScope: false
  riders: # can be defined here for resources that need to be deployed per-Pipeline or per-Vertex

  # the Pipeline definition in Numaflow
  pipeline:
    metadata:
      annotations:
    #    numaflow.numaproj.io/instance: "0" # uncomment for Progressive rollout to set Numaflow Controller instance
        my-templated-annotation: '{{.pipeline-namespace}}-{{.pipeline-name}}'
    spec:
      lifecycle:
        pauseGracePeriodSeconds: 60
      interStepBufferServiceName: my-isbsvc
      vertices:
        - name: in
          scale: 
            #min: 3
            #max: 5
            loopbackSeconds: 180
          
          source:
            # A self data generating source
            generator:
              rpu: 5000
              duration: 1s
        - name: cat
          scale: 
            min: 3
            max: 5
          udf:
            container:
              image: "quay.io/numaio/numaflow-go/map-cat:stable" # A built-in UDF which simply cats the message
              imagePullPolicy: Always
        - name: out
          sink:
            # A simple log printing sink
            log: {}
      edges:
        - from: in
          to: cat
        - from: cat
          to: out

---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pipeline-template
  namespace: example-namespace
spec:
  args:
  - name: upgrading-pipeline-name
  - name: pipeline-namespace
  - name: interval
    value: 60s
  - name: success-limit
    value: "4"
  - name: failure-limit
    value: "6"
  metrics:
  - consecutiveSuccessLimit: '{{args.success-limit}}'
    failureLimit: '{{args.failure-limit}}'
    interval: '{{args.interval}}'
    name: in
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
        query: (vector(1) and on() ((sum(numaflow_forwarder_read_total{namespace="{{args.pipeline-namespace}}",
          pipeline="{{args.upgrading-pipeline-name}}", vertex="in"}) or vector(0))
          == 0)) or (vector(1) and on() ((sum(numaflow_forwarder_ack_total{namespace="{{args.pipeline-namespace}}",
          pipeline="{{args.upgrading-pipeline-name}}", vertex="in"}) or vector(0))
          > 0)) or vector(0)
    successCondition: len(result) > 0 && result[0] > 0
  - consecutiveSuccessLimit: '{{args.success-limit}}'
    failureLimit: '{{args.failure-limit}}'
    interval: '{{args.interval}}'
    name: cat
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
        query: (vector(1) and on() ((sum(numaflow_forwarder_read_total{namespace="{{args.pipeline-namespace}}",
          pipeline="{{args.upgrading-pipeline-name}}", vertex="cat"})
          or vector(0)) == 0)) or (vector(1) and on() ((sum(numaflow_forwarder_ack_total{namespace="{{args.pipeline-namespace}}",
          pipeline="{{args.upgrading-pipeline-name}}", vertex="cat"})
          or vector(0)) > 0)) or vector(0)
    successCondition: len(result) > 0 && result[0] > 0
  - consecutiveSuccessLimit: '{{args.success-limit}}'
    failureLimit: '{{args.failure-limit}}'
    interval: '{{args.interval}}'
    name: out
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
        query: (vector(1) and on() ((sum(numaflow_forwarder_read_total{namespace="{{args.pipeline-namespace}}",
          pipeline="{{args.upgrading-pipeline-name}}", vertex="out"}) or vector(0))
          == 0)) or (vector(1) and on() ((sum(numaflow_forwarder_ack_total{namespace="{{args.pipeline-namespace}}",
          pipeline="{{args.upgrading-pipeline-name}}", vertex="out"}) or vector(0))
          > 0)) or vector(0)
    successCondition: len(result) > 0 && result[0] > 0
