/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/numaproj/numaplane/pkg/apis/numaplane/v1alpha1"
	scheme "github.com/numaproj/numaplane/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ISBServiceRolloutsGetter has a method to return a ISBServiceRolloutInterface.
// A group's client should implement this interface.
type ISBServiceRolloutsGetter interface {
	ISBServiceRollouts(namespace string) ISBServiceRolloutInterface
}

// ISBServiceRolloutInterface has methods to work with ISBServiceRollout resources.
type ISBServiceRolloutInterface interface {
	Create(ctx context.Context, iSBServiceRollout *v1alpha1.ISBServiceRollout, opts v1.CreateOptions) (*v1alpha1.ISBServiceRollout, error)
	Update(ctx context.Context, iSBServiceRollout *v1alpha1.ISBServiceRollout, opts v1.UpdateOptions) (*v1alpha1.ISBServiceRollout, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iSBServiceRollout *v1alpha1.ISBServiceRollout, opts v1.UpdateOptions) (*v1alpha1.ISBServiceRollout, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ISBServiceRollout, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ISBServiceRolloutList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ISBServiceRollout, err error)
	ISBServiceRolloutExpansion
}

// iSBServiceRollouts implements ISBServiceRolloutInterface
type iSBServiceRollouts struct {
	*gentype.ClientWithList[*v1alpha1.ISBServiceRollout, *v1alpha1.ISBServiceRolloutList]
}

// newISBServiceRollouts returns a ISBServiceRollouts
func newISBServiceRollouts(c *NumaplaneV1alpha1Client, namespace string) *iSBServiceRollouts {
	return &iSBServiceRollouts{
		gentype.NewClientWithList[*v1alpha1.ISBServiceRollout, *v1alpha1.ISBServiceRolloutList](
			"isbservicerollouts",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.ISBServiceRollout { return &v1alpha1.ISBServiceRollout{} },
			func() *v1alpha1.ISBServiceRolloutList { return &v1alpha1.ISBServiceRolloutList{} }),
	}
}
