/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/numaproj/numaplane/pkg/apis/numaplane/v1alpha1"
	scheme "github.com/numaproj/numaplane/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MonoVertexRolloutsGetter has a method to return a MonoVertexRolloutInterface.
// A group's client should implement this interface.
type MonoVertexRolloutsGetter interface {
	MonoVertexRollouts(namespace string) MonoVertexRolloutInterface
}

// MonoVertexRolloutInterface has methods to work with MonoVertexRollout resources.
type MonoVertexRolloutInterface interface {
	Create(ctx context.Context, monoVertexRollout *v1alpha1.MonoVertexRollout, opts v1.CreateOptions) (*v1alpha1.MonoVertexRollout, error)
	Update(ctx context.Context, monoVertexRollout *v1alpha1.MonoVertexRollout, opts v1.UpdateOptions) (*v1alpha1.MonoVertexRollout, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, monoVertexRollout *v1alpha1.MonoVertexRollout, opts v1.UpdateOptions) (*v1alpha1.MonoVertexRollout, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MonoVertexRollout, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MonoVertexRolloutList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MonoVertexRollout, err error)
	MonoVertexRolloutExpansion
}

// monoVertexRollouts implements MonoVertexRolloutInterface
type monoVertexRollouts struct {
	*gentype.ClientWithList[*v1alpha1.MonoVertexRollout, *v1alpha1.MonoVertexRolloutList]
}

// newMonoVertexRollouts returns a MonoVertexRollouts
func newMonoVertexRollouts(c *NumaplaneV1alpha1Client, namespace string) *monoVertexRollouts {
	return &monoVertexRollouts{
		gentype.NewClientWithList[*v1alpha1.MonoVertexRollout, *v1alpha1.MonoVertexRolloutList](
			"monovertexrollouts",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.MonoVertexRollout { return &v1alpha1.MonoVertexRollout{} },
			func() *v1alpha1.MonoVertexRolloutList { return &v1alpha1.MonoVertexRolloutList{} }),
	}
}
