/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/numaproj/numaplane/pkg/apis/numaplane/v1alpha1"
	scheme "github.com/numaproj/numaplane/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NumaflowControllerRolloutsGetter has a method to return a NumaflowControllerRolloutInterface.
// A group's client should implement this interface.
type NumaflowControllerRolloutsGetter interface {
	NumaflowControllerRollouts(namespace string) NumaflowControllerRolloutInterface
}

// NumaflowControllerRolloutInterface has methods to work with NumaflowControllerRollout resources.
type NumaflowControllerRolloutInterface interface {
	Create(ctx context.Context, numaflowControllerRollout *v1alpha1.NumaflowControllerRollout, opts v1.CreateOptions) (*v1alpha1.NumaflowControllerRollout, error)
	Update(ctx context.Context, numaflowControllerRollout *v1alpha1.NumaflowControllerRollout, opts v1.UpdateOptions) (*v1alpha1.NumaflowControllerRollout, error)
	UpdateStatus(ctx context.Context, numaflowControllerRollout *v1alpha1.NumaflowControllerRollout, opts v1.UpdateOptions) (*v1alpha1.NumaflowControllerRollout, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NumaflowControllerRollout, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NumaflowControllerRolloutList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NumaflowControllerRollout, err error)
	NumaflowControllerRolloutExpansion
}

// numaflowControllerRollouts implements NumaflowControllerRolloutInterface
type numaflowControllerRollouts struct {
	client rest.Interface
	ns     string
}

// newNumaflowControllerRollouts returns a NumaflowControllerRollouts
func newNumaflowControllerRollouts(c *NumaplaneV1alpha1Client, namespace string) *numaflowControllerRollouts {
	return &numaflowControllerRollouts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the numaflowControllerRollout, and returns the corresponding numaflowControllerRollout object, and an error if there is any.
func (c *numaflowControllerRollouts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NumaflowControllerRollout, err error) {
	result = &v1alpha1.NumaflowControllerRollout{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("numaflowcontrollerrollouts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NumaflowControllerRollouts that match those selectors.
func (c *numaflowControllerRollouts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NumaflowControllerRolloutList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NumaflowControllerRolloutList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("numaflowcontrollerrollouts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested numaflowControllerRollouts.
func (c *numaflowControllerRollouts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("numaflowcontrollerrollouts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a numaflowControllerRollout and creates it.  Returns the server's representation of the numaflowControllerRollout, and an error, if there is any.
func (c *numaflowControllerRollouts) Create(ctx context.Context, numaflowControllerRollout *v1alpha1.NumaflowControllerRollout, opts v1.CreateOptions) (result *v1alpha1.NumaflowControllerRollout, err error) {
	result = &v1alpha1.NumaflowControllerRollout{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("numaflowcontrollerrollouts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(numaflowControllerRollout).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a numaflowControllerRollout and updates it. Returns the server's representation of the numaflowControllerRollout, and an error, if there is any.
func (c *numaflowControllerRollouts) Update(ctx context.Context, numaflowControllerRollout *v1alpha1.NumaflowControllerRollout, opts v1.UpdateOptions) (result *v1alpha1.NumaflowControllerRollout, err error) {
	result = &v1alpha1.NumaflowControllerRollout{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("numaflowcontrollerrollouts").
		Name(numaflowControllerRollout.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(numaflowControllerRollout).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *numaflowControllerRollouts) UpdateStatus(ctx context.Context, numaflowControllerRollout *v1alpha1.NumaflowControllerRollout, opts v1.UpdateOptions) (result *v1alpha1.NumaflowControllerRollout, err error) {
	result = &v1alpha1.NumaflowControllerRollout{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("numaflowcontrollerrollouts").
		Name(numaflowControllerRollout.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(numaflowControllerRollout).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the numaflowControllerRollout and deletes it. Returns an error if one occurs.
func (c *numaflowControllerRollouts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("numaflowcontrollerrollouts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *numaflowControllerRollouts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("numaflowcontrollerrollouts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched numaflowControllerRollout.
func (c *numaflowControllerRollouts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NumaflowControllerRollout, err error) {
	result = &v1alpha1.NumaflowControllerRollout{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("numaflowcontrollerrollouts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
