/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	numaplanev1alpha1 "github.com/numaproj/numaplane/pkg/apis/numaplane/v1alpha1"
	scheme "github.com/numaproj/numaplane/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NumaflowControllersGetter has a method to return a NumaflowControllerInterface.
// A group's client should implement this interface.
type NumaflowControllersGetter interface {
	NumaflowControllers(namespace string) NumaflowControllerInterface
}

// NumaflowControllerInterface has methods to work with NumaflowController resources.
type NumaflowControllerInterface interface {
	Create(ctx context.Context, numaflowController *numaplanev1alpha1.NumaflowController, opts v1.CreateOptions) (*numaplanev1alpha1.NumaflowController, error)
	Update(ctx context.Context, numaflowController *numaplanev1alpha1.NumaflowController, opts v1.UpdateOptions) (*numaplanev1alpha1.NumaflowController, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, numaflowController *numaplanev1alpha1.NumaflowController, opts v1.UpdateOptions) (*numaplanev1alpha1.NumaflowController, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*numaplanev1alpha1.NumaflowController, error)
	List(ctx context.Context, opts v1.ListOptions) (*numaplanev1alpha1.NumaflowControllerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *numaplanev1alpha1.NumaflowController, err error)
	NumaflowControllerExpansion
}

// numaflowControllers implements NumaflowControllerInterface
type numaflowControllers struct {
	*gentype.ClientWithList[*numaplanev1alpha1.NumaflowController, *numaplanev1alpha1.NumaflowControllerList]
}

// newNumaflowControllers returns a NumaflowControllers
func newNumaflowControllers(c *NumaplaneV1alpha1Client, namespace string) *numaflowControllers {
	return &numaflowControllers{
		gentype.NewClientWithList[*numaplanev1alpha1.NumaflowController, *numaplanev1alpha1.NumaflowControllerList](
			"numaflowcontrollers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *numaplanev1alpha1.NumaflowController { return &numaplanev1alpha1.NumaflowController{} },
			func() *numaplanev1alpha1.NumaflowControllerList { return &numaplanev1alpha1.NumaflowControllerList{} },
		),
	}
}
