/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/numaproj/numaplane/pkg/apis/numaplane/v1alpha1"
	scheme "github.com/numaproj/numaplane/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PipelineRolloutsGetter has a method to return a PipelineRolloutInterface.
// A group's client should implement this interface.
type PipelineRolloutsGetter interface {
	PipelineRollouts(namespace string) PipelineRolloutInterface
}

// PipelineRolloutInterface has methods to work with PipelineRollout resources.
type PipelineRolloutInterface interface {
	Create(ctx context.Context, pipelineRollout *v1alpha1.PipelineRollout, opts v1.CreateOptions) (*v1alpha1.PipelineRollout, error)
	Update(ctx context.Context, pipelineRollout *v1alpha1.PipelineRollout, opts v1.UpdateOptions) (*v1alpha1.PipelineRollout, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, pipelineRollout *v1alpha1.PipelineRollout, opts v1.UpdateOptions) (*v1alpha1.PipelineRollout, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PipelineRollout, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PipelineRolloutList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PipelineRollout, err error)
	PipelineRolloutExpansion
}

// pipelineRollouts implements PipelineRolloutInterface
type pipelineRollouts struct {
	*gentype.ClientWithList[*v1alpha1.PipelineRollout, *v1alpha1.PipelineRolloutList]
}

// newPipelineRollouts returns a PipelineRollouts
func newPipelineRollouts(c *NumaplaneV1alpha1Client, namespace string) *pipelineRollouts {
	return &pipelineRollouts{
		gentype.NewClientWithList[*v1alpha1.PipelineRollout, *v1alpha1.PipelineRolloutList](
			"pipelinerollouts",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.PipelineRollout { return &v1alpha1.PipelineRollout{} },
			func() *v1alpha1.PipelineRolloutList { return &v1alpha1.PipelineRolloutList{} }),
	}
}
