/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/numaproj/numaplane/pkg/apis/numaplane/v1alpha1"
	scheme "github.com/numaproj/numaplane/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PipelineRolloutsGetter has a method to return a PipelineRolloutInterface.
// A group's client should implement this interface.
type PipelineRolloutsGetter interface {
	PipelineRollouts(namespace string) PipelineRolloutInterface
}

// PipelineRolloutInterface has methods to work with PipelineRollout resources.
type PipelineRolloutInterface interface {
	Create(ctx context.Context, pipelineRollout *v1alpha1.PipelineRollout, opts v1.CreateOptions) (*v1alpha1.PipelineRollout, error)
	Update(ctx context.Context, pipelineRollout *v1alpha1.PipelineRollout, opts v1.UpdateOptions) (*v1alpha1.PipelineRollout, error)
	UpdateStatus(ctx context.Context, pipelineRollout *v1alpha1.PipelineRollout, opts v1.UpdateOptions) (*v1alpha1.PipelineRollout, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PipelineRollout, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PipelineRolloutList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PipelineRollout, err error)
	PipelineRolloutExpansion
}

// pipelineRollouts implements PipelineRolloutInterface
type pipelineRollouts struct {
	client rest.Interface
	ns     string
}

// newPipelineRollouts returns a PipelineRollouts
func newPipelineRollouts(c *NumaplaneV1alpha1Client, namespace string) *pipelineRollouts {
	return &pipelineRollouts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pipelineRollout, and returns the corresponding pipelineRollout object, and an error if there is any.
func (c *pipelineRollouts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PipelineRollout, err error) {
	result = &v1alpha1.PipelineRollout{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipelinerollouts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PipelineRollouts that match those selectors.
func (c *pipelineRollouts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PipelineRolloutList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PipelineRolloutList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipelinerollouts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pipelineRollouts.
func (c *pipelineRollouts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pipelinerollouts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a pipelineRollout and creates it.  Returns the server's representation of the pipelineRollout, and an error, if there is any.
func (c *pipelineRollouts) Create(ctx context.Context, pipelineRollout *v1alpha1.PipelineRollout, opts v1.CreateOptions) (result *v1alpha1.PipelineRollout, err error) {
	result = &v1alpha1.PipelineRollout{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pipelinerollouts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pipelineRollout).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a pipelineRollout and updates it. Returns the server's representation of the pipelineRollout, and an error, if there is any.
func (c *pipelineRollouts) Update(ctx context.Context, pipelineRollout *v1alpha1.PipelineRollout, opts v1.UpdateOptions) (result *v1alpha1.PipelineRollout, err error) {
	result = &v1alpha1.PipelineRollout{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pipelinerollouts").
		Name(pipelineRollout.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pipelineRollout).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *pipelineRollouts) UpdateStatus(ctx context.Context, pipelineRollout *v1alpha1.PipelineRollout, opts v1.UpdateOptions) (result *v1alpha1.PipelineRollout, err error) {
	result = &v1alpha1.PipelineRollout{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pipelinerollouts").
		Name(pipelineRollout.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pipelineRollout).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the pipelineRollout and deletes it. Returns an error if one occurs.
func (c *pipelineRollouts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipelinerollouts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pipelineRollouts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipelinerollouts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched pipelineRollout.
func (c *pipelineRollouts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PipelineRollout, err error) {
	result = &v1alpha1.PipelineRollout{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pipelinerollouts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
