import exp from "constants";

export const HEALTHY = "HEALTHY";
export const UNHEALTHY = "UNHEALTHY";
export const PROGRESSING = "PROGRESSING";
export const SUCCESSFUL = "SUCCESSFUL";
export const RUNNING = "RUNNING";
export const FAILURE = "FAILURE";
export const DEGRADED = "DEGRADED";
export const ERROR = "ERROR";
export const POD = "Pod";
export const REPLICA_SET = "ReplicaSet";
export const ROLLOUT = "Rollout";
export const CANARY = "CANARY";
export const REVISION = "REVISION";
export const STATUS_REASON = "Status Reason";
export const ANALYSIS_RUN = "AnalysisRun";
export const INTUIT_DOMAIN = "intuit.com";
export const ISB_SERVICE_ROLLOUT = "ISBServiceRollout";
export const NUMAFLOW_CONTROLLER_ROLLOUT = "NumaflowControllerRollout";
export const PIPELINE_ROLLOUT = "PipelineRollout";
