/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/numaproj/numaplane/pkg/apis/numaplane/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNumaflowControllerRollouts implements NumaflowControllerRolloutInterface
type FakeNumaflowControllerRollouts struct {
	Fake *FakeNumaplaneV1alpha1
	ns   string
}

var numaflowcontrollerrolloutsResource = v1alpha1.SchemeGroupVersion.WithResource("numaflowcontrollerrollouts")

var numaflowcontrollerrolloutsKind = v1alpha1.SchemeGroupVersion.WithKind("NumaflowControllerRollout")

// Get takes name of the numaflowControllerRollout, and returns the corresponding numaflowControllerRollout object, and an error if there is any.
func (c *FakeNumaflowControllerRollouts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NumaflowControllerRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(numaflowcontrollerrolloutsResource, c.ns, name), &v1alpha1.NumaflowControllerRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NumaflowControllerRollout), err
}

// List takes label and field selectors, and returns the list of NumaflowControllerRollouts that match those selectors.
func (c *FakeNumaflowControllerRollouts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NumaflowControllerRolloutList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(numaflowcontrollerrolloutsResource, numaflowcontrollerrolloutsKind, c.ns, opts), &v1alpha1.NumaflowControllerRolloutList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NumaflowControllerRolloutList{ListMeta: obj.(*v1alpha1.NumaflowControllerRolloutList).ListMeta}
	for _, item := range obj.(*v1alpha1.NumaflowControllerRolloutList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested numaflowControllerRollouts.
func (c *FakeNumaflowControllerRollouts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(numaflowcontrollerrolloutsResource, c.ns, opts))

}

// Create takes the representation of a numaflowControllerRollout and creates it.  Returns the server's representation of the numaflowControllerRollout, and an error, if there is any.
func (c *FakeNumaflowControllerRollouts) Create(ctx context.Context, numaflowControllerRollout *v1alpha1.NumaflowControllerRollout, opts v1.CreateOptions) (result *v1alpha1.NumaflowControllerRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(numaflowcontrollerrolloutsResource, c.ns, numaflowControllerRollout), &v1alpha1.NumaflowControllerRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NumaflowControllerRollout), err
}

// Update takes the representation of a numaflowControllerRollout and updates it. Returns the server's representation of the numaflowControllerRollout, and an error, if there is any.
func (c *FakeNumaflowControllerRollouts) Update(ctx context.Context, numaflowControllerRollout *v1alpha1.NumaflowControllerRollout, opts v1.UpdateOptions) (result *v1alpha1.NumaflowControllerRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(numaflowcontrollerrolloutsResource, c.ns, numaflowControllerRollout), &v1alpha1.NumaflowControllerRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NumaflowControllerRollout), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNumaflowControllerRollouts) UpdateStatus(ctx context.Context, numaflowControllerRollout *v1alpha1.NumaflowControllerRollout, opts v1.UpdateOptions) (*v1alpha1.NumaflowControllerRollout, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(numaflowcontrollerrolloutsResource, "status", c.ns, numaflowControllerRollout), &v1alpha1.NumaflowControllerRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NumaflowControllerRollout), err
}

// Delete takes name of the numaflowControllerRollout and deletes it. Returns an error if one occurs.
func (c *FakeNumaflowControllerRollouts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(numaflowcontrollerrolloutsResource, c.ns, name, opts), &v1alpha1.NumaflowControllerRollout{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNumaflowControllerRollouts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(numaflowcontrollerrolloutsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NumaflowControllerRolloutList{})
	return err
}

// Patch applies the patch and returns the patched numaflowControllerRollout.
func (c *FakeNumaflowControllerRollouts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NumaflowControllerRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(numaflowcontrollerrolloutsResource, c.ns, name, pt, data, subresources...), &v1alpha1.NumaflowControllerRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NumaflowControllerRollout), err
}
