/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/numaproj/numaplane/pkg/apis/numaplane/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeISBServiceRollouts implements ISBServiceRolloutInterface
type FakeISBServiceRollouts struct {
	Fake *FakeNumaplaneV1alpha1
	ns   string
}

var isbservicerolloutsResource = v1alpha1.SchemeGroupVersion.WithResource("isbservicerollouts")

var isbservicerolloutsKind = v1alpha1.SchemeGroupVersion.WithKind("ISBServiceRollout")

// Get takes name of the iSBServiceRollout, and returns the corresponding iSBServiceRollout object, and an error if there is any.
func (c *FakeISBServiceRollouts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ISBServiceRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(isbservicerolloutsResource, c.ns, name), &v1alpha1.ISBServiceRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ISBServiceRollout), err
}

// List takes label and field selectors, and returns the list of ISBServiceRollouts that match those selectors.
func (c *FakeISBServiceRollouts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ISBServiceRolloutList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(isbservicerolloutsResource, isbservicerolloutsKind, c.ns, opts), &v1alpha1.ISBServiceRolloutList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ISBServiceRolloutList{ListMeta: obj.(*v1alpha1.ISBServiceRolloutList).ListMeta}
	for _, item := range obj.(*v1alpha1.ISBServiceRolloutList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iSBServiceRollouts.
func (c *FakeISBServiceRollouts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(isbservicerolloutsResource, c.ns, opts))

}

// Create takes the representation of a iSBServiceRollout and creates it.  Returns the server's representation of the iSBServiceRollout, and an error, if there is any.
func (c *FakeISBServiceRollouts) Create(ctx context.Context, iSBServiceRollout *v1alpha1.ISBServiceRollout, opts v1.CreateOptions) (result *v1alpha1.ISBServiceRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(isbservicerolloutsResource, c.ns, iSBServiceRollout), &v1alpha1.ISBServiceRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ISBServiceRollout), err
}

// Update takes the representation of a iSBServiceRollout and updates it. Returns the server's representation of the iSBServiceRollout, and an error, if there is any.
func (c *FakeISBServiceRollouts) Update(ctx context.Context, iSBServiceRollout *v1alpha1.ISBServiceRollout, opts v1.UpdateOptions) (result *v1alpha1.ISBServiceRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(isbservicerolloutsResource, c.ns, iSBServiceRollout), &v1alpha1.ISBServiceRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ISBServiceRollout), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeISBServiceRollouts) UpdateStatus(ctx context.Context, iSBServiceRollout *v1alpha1.ISBServiceRollout, opts v1.UpdateOptions) (*v1alpha1.ISBServiceRollout, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(isbservicerolloutsResource, "status", c.ns, iSBServiceRollout), &v1alpha1.ISBServiceRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ISBServiceRollout), err
}

// Delete takes name of the iSBServiceRollout and deletes it. Returns an error if one occurs.
func (c *FakeISBServiceRollouts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(isbservicerolloutsResource, c.ns, name, opts), &v1alpha1.ISBServiceRollout{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeISBServiceRollouts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(isbservicerolloutsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ISBServiceRolloutList{})
	return err
}

// Patch applies the patch and returns the patched iSBServiceRollout.
func (c *FakeISBServiceRollouts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ISBServiceRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(isbservicerolloutsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ISBServiceRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ISBServiceRollout), err
}
